# Generated by Django 5.1.4 on 2025-01-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='imoveis/', verbose_name='imagem corretor')),
                ('senha', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('comercial', 'Imóvel Comercial')], max_length=20)),
                ('descricao', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, help_text='Área total do imóvel em metros quadrados', max_digits=6)),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('vagas_garagem', models.IntegerField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('vendido', 'Vendido'), ('indisponivel', 'Indisponível')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_parceiro', models.CharField(choices=[('imobiliaria', 'Imobiliária'), ('financiamento', 'Financiamento'), ('servicos', 'Serviços'), ('outros', 'Outros')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=100)),
                ('bi', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/', verbose_name='Imagem do Imóvel')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Imagem')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField()),
                ('data_feedback', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.cliente')),
                ('corretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corretora_app.corretor')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('escritura', 'Escritura'), ('iptu', 'IPTU'), ('alvara', 'Alvará')], max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos_imoveis/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('aluguel', 'Aluguel')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.cliente')),
                ('corretor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretora_app.corretor')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], max_length=50)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.corretor')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.cliente')),
                ('corretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corretora_app.corretor')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=50)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('total_vendas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_imoveis_vendidos', models.IntegerField()),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.corretor')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretora_app.vendedor'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_favorito', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
            options={
                'unique_together': {('cliente', 'imovel')},
            },
        ),
    ]
