# Generated by Django 5.1.4 on 2025-01-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAdicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_varanda', models.BooleanField(default=False)),
                ('exterior_piscina_coletiva', models.BooleanField(default=False)),
                ('exterior_estacionamento_privativo', models.BooleanField(default=False)),
                ('exterior_churrasqueira', models.BooleanField(default=False)),
                ('exterior_campos_polidesportivos', models.BooleanField(default=False)),
                ('interior_suites', models.IntegerField(default=0)),
                ('interior_roupeiros_embutidos', models.BooleanField(default=False)),
                ('interior_cozinha_equipada', models.BooleanField(default=False)),
                ('interior_ar_condicionado', models.BooleanField(default=False)),
                ('segurança_24h', models.BooleanField(default=False)),
                ('reservatorio_agua', models.BooleanField(default=False)),
                ('ginásio', models.BooleanField(default=False)),
                ('gerador', models.BooleanField(default=False)),
                ('area_servico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/galeria/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_lance', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('lance_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('boleto', 'Boleto'), ('cartao', 'Cartão'), ('pix', 'Pix')], max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou')], default='pendente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ofertado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Publicidade_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/publicidade_home/')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField()),
                ('taxa_juros', models.FloatField()),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imoveis/', verbose_name='Imagem Corretor')),
                ('codigo', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('corretor', 'Corretor'), ('empresa', 'Empresa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imovel',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='corretor',
        ),
        migrations.RemoveField(
            model_name='imagemimovel',
            name='imovel',
        ),
        migrations.DeleteModel(
            name='Parceiro',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/', verbose_name='Imagem do imóvel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ex: vivenda T5'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='documentoimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('comercial', 'Imóvel Comercial'), ('escritorio', 'Escritório')], max_length=20),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao_imovel', to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='dadosadicionais',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='dados_adicionais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imovel_dados', to='corretora_app.dadosadicionais'),
        ),
        migrations.AddField(
            model_name='galeriaimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='leilao',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='lance',
            name='leilao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.leilao'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.contrato'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='simulacaofinanciamento',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
        ),
        migrations.AddField(
            model_name='simulacaofinanciamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
        ),
        migrations.AddField(
            model_name='lance',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='locatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='corretor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'corretor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='corretor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'corretor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='corretor',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'corretor'}, on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='corretor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'corretor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_vendidos', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='relatoriovendas',
            name='corretor',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'corretor'}, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_vendas_corretor', to='corretora_app.usuario'),
        ),
        migrations.AddField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='visita',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
        migrations.DeleteModel(
            name='ImagemImovel',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.DeleteModel(
            name='Corretor',
        ),
    ]
