# Generated by Django 5.1.4 on 2025-01-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imoveis/', verbose_name='Imagem Corretor')),
                ('bi', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('corretor', 'Corretor')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imovel',
        ),
        migrations.RemoveField(
            model_name='imagemimovel',
            name='imovel',
        ),
        migrations.DeleteModel(
            name='Parceiro',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='documentoimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao_imovel', to='corretora_app.imovel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='corretor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'corretor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='corretor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'corretor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='corretor',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'corretor'}, on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='corretor',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'corretor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='corretor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'corretor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_corretor', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_vendidos', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='relatoriovendas',
            name='corretor',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'corretor'}, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_vendas_corretor', to='corretora_app.usuario'),
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
        migrations.DeleteModel(
            name='ImagemImovel',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.DeleteModel(
            name='Corretor',
        ),
    ]
