# Generated by Django 5.1.4 on 2025-01-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0002_dadosadicionais_galeriaimovel_lance_leilao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='dados_adicionais',
        ),
    ]
