# Generated by Django 5.1.4 on 2025-01-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0003_remove_imovel_dados_adicionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/galeria/', verbose_name='Imagem Adicional')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do vídeo'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/', verbose_name='Imagem Principal do Imóvel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas_garagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagens_adicionais',
            field=models.ManyToManyField(blank=True, related_name='imoveis', to='corretora_app.imagemadicional'),
        ),
    ]
