# Generated by Django 5.1.4 on 2025-01-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0004_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/', verbose_name='Imagem Corretor'),
        ),
    ]
