# Generated by Django 5.1.4 on 2025-01-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0004_imagemadicional_imovel_video_alter_imovel_banheiros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='hora_agendada',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
