# Generated by Django 5.1.4 on 2025-01-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0005_imovel_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ex: vivenda T5'),
        ),
    ]
