# Generated by Django 5.1.4 on 2025-01-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0006_imovel_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAdicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_varanda', models.BooleanField(default=False)),
                ('exterior_piscina_coletiva', models.BooleanField(default=False)),
                ('exterior_estacionamento_privativo', models.BooleanField(default=False)),
                ('exterior_churrasqueira', models.BooleanField(default=False)),
                ('exterior_campos_polidesportivos', models.BooleanField(default=False)),
                ('interior_suites', models.IntegerField(default=0)),
                ('interior_roupeiros_embutidos', models.BooleanField(default=False)),
                ('interior_cozinha_equipada', models.BooleanField(default=False)),
                ('interior_ar_condicionado', models.BooleanField(default=False)),
                ('segurança_24h', models.BooleanField(default=False)),
                ('reservatorio_agua', models.BooleanField(default=False)),
                ('ginásio', models.BooleanField(default=False)),
                ('gerador', models.BooleanField(default=False)),
                ('area_servico', models.BooleanField(default=False)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_adicionais', to='corretora_app.imovel')),
            ],
        ),
    ]
