# Generated by Django 5.1.4 on 2025-01-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0006_alter_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_agendada',
            new_name='data_hora_agendada',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hora_agendada',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado')], max_length=10),
        ),
    ]
