# Generated by Django 5.1.4 on 2025-01-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0007_dadosadicionais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='valor',
            new_name='valor_mensal',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='data_favorito',
            new_name='data_adicionado',
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='corretor',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='locatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel'),
        ),
        migrations.CreateModel(
            name='GaleriaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/galeria/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('lance_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_lance', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.leilao')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('boleto', 'Boleto'), ('cartao', 'Cartão'), ('pix', 'Pix')], max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou')], default='pendente', max_length=15)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ofertado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=15)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField()),
                ('taxa_juros', models.FloatField()),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=15)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.imovel')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora_app.usuario')),
            ],
        ),
    ]
