# Generated by Django 5.1.4 on 2025-01-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0007_horaagendamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='corretor',
        ),
        migrations.AddField(
            model_name='imovel',
            name='corretores',
            field=models.ManyToManyField(limit_choices_to={'tipo_usuario': 'corretor'}, related_name='imoveis', to='corretora_app.usuario'),
        ),
    ]
