# Generated by Django 5.1.4 on 2025-01-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0008_rename_valor_contrato_valor_mensal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='data_adicionado',
            new_name='data_favorito',
        ),
        migrations.AlterField(
            model_name='favorito',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_cliente', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_imovel', to='corretora_app.imovel'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('cliente', 'imovel')},
        ),
    ]
