# Generated by Django 5.1.6 on 2025-02-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0008_remove_imovel_corretor_imovel_corretores'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='apresentar',
            field=models.BooleanField(default=False, verbose_name='Apresentar na Home'),
        ),
    ]
