# Generated by Django 5.1.6 on 2025-02-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0010_alter_imovel_area_alter_imovel_banheiros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='anunciante_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Anunciante'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='anunciante_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Anunciante'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='anunciante_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Anunciante'),
        ),
        migrations.AlterField(
            model_name='galeriaimovel',
            name='imagem',
            field=models.ImageField(upload_to='imoveis/galeria/', verbose_name='Imagem da Galeria'),
        ),
    ]
