# Generated by Django 5.1.6 on 2025-02-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0011_imovel_anunciante_email_imovel_anunciante_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='anunciante_email',
            new_name='email_anunciante',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='anunciante_nome',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='anunciante_telefone',
        ),
        migrations.AddField(
            model_name='imovel',
            name='nome_anunciante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Anunciante'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='telefone_anunciante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Anunciante'),
        ),
    ]
