# Generated by Django 5.1.6 on 2025-02-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0012_rename_anunciante_email_imovel_email_anunciante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosadicionais',
            old_name='ginásio',
            new_name='ginasio',
        ),
        migrations.RenameField(
            model_name='dadosadicionais',
            old_name='segurança_24h',
            new_name='interior_internet',
        ),
        migrations.AddField(
            model_name='dadosadicionais',
            name='interior_jacuzzi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadosadicionais',
            name='interior_maquina_louca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadosadicionais',
            name='interior_maquina_roupa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadosadicionais',
            name='mobilado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=10),
        ),
        migrations.AddField(
            model_name='dadosadicionais',
            name='seguranca_24h',
            field=models.BooleanField(default=False),
        ),
    ]
