# Generated by Django 5.1.6 on 2025-02-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0013_rename_ginásio_dadosadicionais_ginasio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destacar Imóvel'),
        ),
    ]
