# Generated by Django 5.1.6 on 2025-02-08 03:56

import corretora_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0014_imovel_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(blank=True, default=corretora_app.models.Imovel.default_image_path, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
