# Generated by Django 5.1.6 on 2025-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0016_alter_imovel_corretores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='corretores',
            field=models.ManyToManyField(limit_choices_to={'tipo_usuario': 'corretor'}, related_name='imoveis', to='corretora_app.usuario'),
        ),
    ]
