# Generated by Django 5.1.6 on 2025-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0018_alter_imovel_corretores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='email_anunciante',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-mail do Anunciante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='nome_anunciante',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome do Anunciante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='telefone_anunciante',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefone do Anunciante'),
            preserve_default=False,
        ),
    ]
