# Generated by Django 5.1.6 on 2025-02-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0019_alter_imovel_email_anunciante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Área total do imóvel em metros quadrados', max_digits=255),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=255),
        ),
    ]
