# Generated by Django 5.1.6 on 2025-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0020_alter_imovel_area_alter_imovel_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Área total do imóvel em metros quadrados', max_digits=255, null=True),
        ),
    ]
