# Generated by Django 5.1.6 on 2025-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0022_alter_imovel_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('descricao', models.TextField()),
                ('apresentar', models.BooleanField(default=False, verbose_name='Apresentar na Home')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='depoimentos/', verbose_name='Imagem')),
            ],
        ),
    ]
