# Generated by Django 5.1.6 on 2025-02-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0023_depoimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_cadastrados', to='corretora_app.usuario'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='email_anunciante',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Anunciante'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='nome_anunciante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Anunciante'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='telefone_anunciante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Anunciante'),
        ),
    ]
