# Generated by Django 4.1.7 on 2025-03-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora_app', '0024_imovel_usuario_alter_imovel_email_anunciante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='usuario',
        ),
    ]
